import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import svelte from 'eslint-plugin-svelte';
import globals from 'globals';

export default [
	js.configs.recommended,
	...tseslint.configs.recommended,
	...svelte.configs['flat/recommended'],
	{
		files: ['**/*.svelte', '**/*.svelte.ts'],
		languageOptions: {
			parserOptions: {
				// eslint-plugin-svelte delegates <script> parsing to this parser;
				// without it, TS annotations in lang="ts" blocks fail to parse.
				parser: tseslint.parser
			}
		}
	},
	{
		languageOptions: {
			globals: { ...globals.browser, ...globals.node }
		},
		rules: {
			'no-console': 'off'
		}
	},
	{
		ignores: ['build/', '.svelte-kit/', 'dist/', 'src/lib/db/migrations/', 'src/lib/components/ui/', 'brag-output*/'] // components/ui: generated by shadcn-svelte
	}
];
